spring.application.name=demo
server.port=8080

spring.security.user.name=${SECURITY_USERNAME:abdelhafid}
spring.security.user.password=${SECURITY_PASSWORD:12345}

spring.datasource.url=jdbc:h2:mem:Automobile
spring.datasource.username=auto
spring.datasource.password=K130309980
spring.datasource.driver-class-name=org.h2.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true





