spring.application.name=demo
server.port=8090

spring.security.user.name=${SECURITY_USERNAME:abdelhafid}
spring.security.user.password=${SECURITY_PASSWORD:12345}



#Postgres Data base
spring.datasource.url=jdbc:postgresql://localhost:5432/automobile
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update



spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/AutomobileRealm
spring.security.oauth2.client.registration.keycloak.client-id=AutomobileClient
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/AutomobileRealm







