spring.application.name=demo
server.port=8080

spring.datasource.url=jdbc:h2:mem:Automobile
spring.datasource.username=auto
spring.datasource.password=K130309980
spring.datasource.driver-class-name=org.h2.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret = 3q2+7wDjR5mZpQkX4vWxYz1234567890abcdefghijk=

auth.token.jwtSecret=3c961343715c0b11546995648a379fb3cf17d23d8c199bfd0a5e7b233a010484
auth.token.expirationInMils=3600000





